### ISSUE TITLE
Make it possible to pass country, barcode and store as URL parameters

### ISSUE THREAD

**Issue by teolemon** [oricdev/off_product_comparator#3]
Make it possible to pass country, barcode and store as URL parameters, so that it can be queried from a website or a mobile app easily.

**Comment by oricdev** [comment]
Same as for #4 
This is already the case, but i was hidden by the client side Ajax requests.
There is currently 1 rule: all 3 parameters "barcode", "country", "store" have to be present in the url, even if some are empty. Anf od course, url-encoded.
Examples:
http://tuttifrutti.alwaysdata.net/fetchAjax/?barcode=29005369&country=en%3Agermany&store=
tuttifrutti.alwaysdata.net/fetchAjax/?barcode=3596710024087&country=en%3Afrance&store=auchan
