### ISSUE TITLE
Make it possible to return results as JSON

### ISSUE THREAD

**Issue by teolemon** [oricdev/off_product_comparator#4]
Make it possible to return results as JSON so that it can be reused in a mobile app.

**Comment by oricdev** [comment]
This is already the case, but i was hidden by the client side Ajax requests.
There is currently 1 rule: all 3 parameters "barcode", "country", "store" have to be present in the url, even if some are empty. Anf od course, url-encoded.
Examples:
http://tuttifrutti.alwaysdata.net/fetchAjax/?barcode=29005369&country=en%3Agermany&store=
tuttifrutti.alwaysdata.net/fetchAjax/?barcode=3596710024087&country=en%3Afrance&store=auchan
